#!/usr/bin/env python3
# claude-hook: Stop
# claude-hook: Notification
# claude-hook: PreToolUse AskUserQuestion
"""Play a sound (and post a banner) when the turn comes back to the user.

Replaces the `singularityinc.claude-notifier` VSCode extension, which did the
same job from five JavaScript hooks it wrote into ~/.claude/settings.json
itself. The extension worked; what it did not do was travel. Its sounds lived
in a machine-local config file that `install.sh` neither creates nor knows
about, so a new machine came up silent until someone remembered to install a
VSCode extension -- which is the same "manual step nothing verifies" failure
that `register_hooks.py` exists to remove.

Terminal-agnostic by construction, not by detection: the sound is played by
the operating system rather than by writing BEL to a tty, so a bare terminal,
the VSCode integrated terminal, tmux and an editor task all behave the same.
Nothing here asks which one it is running under, because that question is
what the extension needed to ask and what its fallback path got wrong.

Three events, one file. Splitting them would give three copies of the SOUNDS
table below, and a notifier whose per-event sounds disagree with each other is
worse than one sound for everything.

Depends on nothing outside the standard library, deliberately -- see the same
note in hooks/prose-writing.py: the interpreter that runs a hook is named in
~/.claude/settings.json, a file outside this repo and outside its checks.
"""

import json
import os
import shutil
import subprocess
import sys
from pathlib import Path

# --------------------------------------------------------------------------
# Customization. Edit these; they are the point of the hook being code, and
# they are version-controlled, so a new machine sounds like this one. For a
# single session instead, the environment wins: CLAUDE_NOTIFY_OFF=1 mutes
# everything, CLAUDE_NOTIFY_SOUND_DONE=Tink overrides one reason.
# --------------------------------------------------------------------------

# Sound per reason. On macOS a bare name resolves to
# /System/Library/Sounds/<name>.aiff (Basso, Blow, Bottle, Frog, Funk, Glass,
# Hero, Morse, Ping, Pop, Purr, Sosumi, Submarine, Tink); anything containing
# a path separator is used as a path, so a custom .aiff or .wav works
# anywhere. An empty string silences that reason while leaving the knob
# visible -- deleting the key would make the reason look unsupported.
SOUNDS = {
    "done": "Hero",
    "permission": "Glass",
    "question": "Funk",
    # Silent by default: `done` already fired when the turn ended, so this
    # only ever arrives as a second ping for a turn already announced, and a
    # notifier that repeats itself is one you learn to ignore. The banner
    # still appears -- it costs no noise -- so the reminder is there to look
    # at without interrupting anything. Name a sound here for the audible nag.
    "idle": "",
}

# afplay's -v is a linear multiplier, so 1.0 is the file's own level and
# values above 1 amplify. Ignored on platforms whose player takes no volume.
VOLUME = 1.0

# Desktop banner alongside the sound. The sound says "your turn"; the banner
# says which project, which is what matters when several sessions run at once.
BANNER = True

# --------------------------------------------------------------------------

# Which `Notification` types mean the turn is the user's. The event also
# carries progress and housekeeping types (auth_success, quota_auto_resume_*,
# computer_use_*, elicitation_*, push_notification) that need no answer, and
# pinging on those trains the ear to ignore the ping.
#
# Claude Code matches a Notification hook's `matcher` against this same
# notification_type, so this filter could have lived in settings.json
# instead. It lives here because settings.json is generated by
# register_hooks.py from the marker above and cannot be seen from this file:
# a filter split across the two would drift silently.
NOTIFICATION_REASONS = {
    "permission_prompt": "permission",
    "worker_permission_prompt": "permission",
    "idle_prompt": "idle",
    "agent_needs_input": "idle",
}

# Banner text for reasons the host does not describe itself. Notification
# supplies its own `message` ("Claude needs your permission to use Bash"),
# which is more specific than anything written here, so permission and idle
# only fall back to these.
MESSAGES = {
    "done": "Finished -- your turn",
    "question": "Waiting on your answer",
    "permission": "Needs your permission",
    "idle": "Waiting for your input",
}

MAC_SOUND_DIR = Path("/System/Library/Sounds")
# Absolute paths rather than a PATH lookup, because a hook inherits whatever
# environment the host had and Homebrew's bin is often not on it.
TERMINAL_NOTIFIER = (
    "/opt/homebrew/bin/terminal-notifier",
    "/usr/local/bin/terminal-notifier",
)


def reason(data):
    """Which SOUNDS key this payload deserves, or None to stay quiet."""
    event = data.get("hook_event_name")
    if event == "Stop":
        # A Stop hook that fed something back to the model gets Stop again
        # when the model stops a second time. The turn was already announced
        # on the first pass, so this one is a duplicate.
        if data.get("stop_hook_active"):
            return None
        return "done"
    if event == "Notification":
        return NOTIFICATION_REASONS.get(data.get("notification_type"))
    if event == "PreToolUse":
        # The matcher in settings.json already narrows this, but a hook that
        # depends on a file it cannot read for correctness is a hook that
        # misfires the day that file is edited by hand.
        tool = data.get("tool_name")
        return "question" if tool == "AskUserQuestion" else None
    return None


def muted():
    """Whether this process should stay silent.

    Presence, not value: any non-empty CLAUDE_NOTIFY_OFF mutes. The one-off
    case -- `CLAUDE_NOTIFY_OFF=1 claude` for a session in a quiet room -- is
    the whole point, and a truth-y string parser here would only introduce a
    disagreement about what "0" means.
    """
    return bool(os.environ.get("CLAUDE_NOTIFY_OFF"))


def sound_for(which):
    """The configured sound name for a reason, environment first."""
    return os.environ.get(f"CLAUDE_NOTIFY_SOUND_{which.upper()}", SOUNDS.get(which, ""))


def sound_argv(name):
    """Player command for a sound name, or None if there is nothing to play."""
    if not name:
        return None
    path = name if ("/" in name or os.sep in name) else None
    if sys.platform == "darwin":
        if path is None:
            candidate = MAC_SOUND_DIR / f"{name}.aiff"
            # A name that does not resolve plays nothing rather than making
            # afplay fail invisibly, which looks identical to "sound is off".
            if not candidate.is_file():
                return None
            path = str(candidate)
        return ["afplay", "-v", str(VOLUME), path]
    if path is None:
        # Only macOS has a named system sound set. Elsewhere a bare name has
        # nothing to resolve against, so point SOUNDS at real files.
        return None
    if os.name == "nt":
        # PowerShell single-quoted strings escape ' by doubling it; nothing
        # else is special inside them, so this is the whole escaping rule.
        quoted = path.replace("'", "''")
        return [
            "powershell",
            "-NoProfile",
            "-Command",
            f"(New-Object Media.SoundPlayer '{quoted}').PlaySync()",
        ]
    for player in ("paplay", "aplay"):
        found = shutil.which(player)
        if found:
            return [found, path]
    return None


def banner_argv(title, message):
    """Desktop notification command, or None where there is no notifier."""
    if sys.platform == "darwin":
        for candidate in TERMINAL_NOTIFIER:
            if os.access(candidate, os.X_OK):
                # Preferred when present: osascript banners are attributed to
                # Script Editor and are dropped silently if that app has no
                # notification permission.
                return [candidate, "-title", title, "-message", message]
        # AppleScript string literals escape only backslash and quote.
        script = f'display notification "{applescript(message)}" with title "{applescript(title)}"'
        return ["osascript", "-e", script]
    notify_send = shutil.which("notify-send")
    if notify_send:
        return [notify_send, "--app-name=Claude Code", title, message]
    return None


def applescript(text):
    return text.replace("\\", "\\\\").replace('"', '\\"')


def project(data):
    """Directory name of the session's cwd, or "Claude Code" if unknown.

    The name, not the path: it is a banner title, and several sessions are
    told apart by which project they are in.
    """
    cwd = data.get("cwd")
    if not isinstance(cwd, str) or not cwd:
        return "Claude Code"
    return os.path.basename(os.path.normpath(cwd)) or "Claude Code"


def spawn(argv):
    """Start a command and do not wait for it.

    A Stop hook runs while the user is looking at the prompt, so waiting out
    a one-second sound would add a one-second pause to every turn.
    start_new_session detaches the child from this process group so the sound
    survives the hook exiting; it is accepted and ignored on Windows, so no
    platform branch is needed here.
    """
    try:
        subprocess.Popen(
            argv,
            stdin=subprocess.DEVNULL,
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
            start_new_session=True,
        )
    except OSError:
        # A missing player is not worth failing a turn over, and a hook that
        # writes to stderr writes into the session transcript.
        pass


def main():
    if muted():
        return
    try:
        data = json.load(sys.stdin)
    except ValueError:
        # Malformed stdin declines rather than tracebacks, as in
        # hooks/promotion-check.py and hooks/prose-writing.py.
        return
    # A valid non-object body ("null", "[]", "42") decodes fine and then has
    # no .get, so shape is checked rather than truthiness.
    if not isinstance(data, dict):
        return

    which = reason(data)
    if which is None:
        return

    argv = sound_argv(sound_for(which))
    if argv:
        spawn(argv)

    if not BANNER:
        return
    message = data.get("message") if which in ("permission", "idle") else None
    if not isinstance(message, str) or not message:
        message = MESSAGES.get(which, "Your turn")
    argv = banner_argv(project(data), message)
    if argv:
        spawn(argv)


if __name__ == "__main__":
    main()
